### ISSUE TITLE
How to improve the code

### ISSUE THREAD

**Issue by guuififi** [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration#1]
如果再加入风机、光伏、有载调压和电容器组，决策变量增加，目标函数变为各设备出力成本和损耗成本，我对此程序进行改动时总是无法正常运行，是不是对此程序的positon休整时，因为开关和各设备出力变量类型不相同导致的呢？，请问大致该如何进行修改程序？希望得到您的解答，麻烦了，谢谢您！

**Comment by ZoraTian** [comment]
这个没看到程序我也不太清楚问题出在哪，但是感觉加入决策变量不会不能正常运行，现在我程序中决策变量是每个Switch的状态，应该将其余决策变量加进去就行吧。
不过决策变量这么多的情况下，我个人感觉效果不会好，或者说这种比较简单的粒子群效果不会很好，我建议你可以将风机光伏之类的加入到优化程序中，让粒子群算法还是决策开关状态，然后拓扑定了后用二阶锥之类的优化算法算出各个设备出力，这样效果应该会比较好。

**Comment by ZoraTian** [comment]
> 如果再加入风机、光伏、有载调压和电容器组，决策变量增加，目标函数变为各设备出力成本和损耗成本，我对此程序进行改动时总是无法正常运行，是不是对此程序的positon休整时，因为开关和各设备出力变量类型不相同导致的呢？，请问大致该如何进行修改程序？希望得到您的解答，麻烦了，谢谢您！

这个没看到程序我也不太清楚问题出在哪，但是感觉加入决策变量不会不能正常运行，现在我程序中决策变量是每个Switch的状态，应该将其余决策变量加进去就行吧。
不过决策变量这么多的情况下，我个人感觉效果不会好，或者说这种比较简单的粒子群效果不会很好，我建议你可以将风机光伏之类的加入到优化程序中，让粒子群算法还是决策开关状态，然后拓扑定了后用二阶锥之类的优化算法算出各个设备出力，这样效果应该会比较好。

**Comment by guuififi** [comment]
类似双层优化吗？分成主问题和子问题进行解决。先进行DG优化配置，之后再决定出力。

**Comment by ZoraTian** [comment]
是的，我感觉是这样，我之前做强化学习配电网动态重构就是强化学习学拓扑，然后其余用pypower求解，效果还行



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 8, 2023 16:36 PM
To: ***@***.***&gt;;
Cc: "Zora ***@***.******@***.***&gt;;
Subject: Re: [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration] Howto improve the code (Issue #1)




 
类似双层优化吗？分成主问题和子问题进行解决。先进行DG优化配置，之后再决定出力。

**Comment by guuififi** [comment]
麻烦师兄了，非常感谢您的解答！

**Comment by guuififi** [comment]
您好，很抱歉再次麻烦您！我今天又对代码进行了修改，修改的目的是在11节点加入容量1MVA，有功0.8MW的DG；节点13加入0.4Mvar的电容器组，挡位为0-8，步长0.05Mvar；节点1加入OLTC，节点初始电压0.9pu，调节范围设为[0.9-1.1]，OLTC挡位0-8。在修改程序后运行结果中出现为小数的联络开关，目标函数ploss在最后一次迭代中的值为（-4.3e4），我想过是算法修改的程序错误和算法不收敛，但前者是我比较关注的，程序可以修改成自适应算法改变收敛性。文件中有IEE33_PSO.com和IEEE33_PSOZhuShi.com,两者程序相同，只是在IEEE33_PSOZhuShi.com中，相对于原始程序被修改语句前面加了双百分号以便凸显，case33bw.m的mpc.pload和mpc.qload的11与13行置0以便加入设备。我的matlab为2022a版，文件中还有程序对应名字的文本文件以便使用。谢谢您，麻烦了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration] How to improve the code (Issue #1)





  
如果再加入风机、光伏、有载调压和电容器组，决策变量增加，目标函数变为各设备出力成本和损耗成本，我对此程序进行改动时总是无法正常运行，是不是对此程序的positon休整时，因为开关和各设备出力变量类型不相同导致的呢？，请问大致该如何进行修改程序？希望得到您的解答，麻烦了，谢谢您！
  
这个没看到程序我也不太清楚问题出在哪，但是感觉加入决策变量不会不能正常运行，现在我程序中决策变量是每个Switch的状态，应该将其余决策变量加进去就行吧。
 不过决策变量这么多的情况下，我个人感觉效果不会好，或者说这种比较简单的粒子群效果不会很好，我建议你可以将风机光伏之类的加入到优化程序中，让粒子群算法还是决策开关状态，然后拓扑定了后用二阶锥之类的优化算法算出各个设备出力，这样效果应该会比较好。

**Comment by ZoraTian** [comment]
小数的联络开关感觉像是你在修改我设置的联络开关状态时出现了问题吧，因为粒子群运动时可能是小数，然后我设置了让其变成整数，算法不收敛我就不是很清楚了，是不是你在哪修改的时候有错误？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration] How to improve the code (Issue #1)





 您好，很抱歉再次麻烦您！我今天又对代码进行了修改，修改的目的是在11节点加入容量1MVA，有功0.8MW的DG；节点13加入0.4Mvar的电容器组，挡位为0-8，步长0.05Mvar；节点1加入OLTC，节点初始电压0.9pu，调节范围设为[0.9-1.1]，OLTC挡位0-8。在修改程序后运行结果中出现为小数的联络开关，目标函数ploss在最后一次迭代中的值为（-4.3e4），我想过是算法修改的程序错误和算法不收敛，但前者是我比较关注的，程序可以修改成自适应算法改变收敛性。文件中有IEE33_PSO.com和IEEE33_PSOZhuShi.com,两者程序相同，只是在IEEE33_PSOZhuShi.com中，相对于原始程序被修改语句前面加了双百分号以便凸显，case33bw.m的mpc.pload和mpc.qload的11与13行置0以便加入设备。我的matlab为2022a版，文件中还有程序对应名字的文本文件以便使用。谢谢您，麻烦了！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月8日(星期三) 下午3:13 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration] How to improve the code (Issue #1) 
 
 
 
 
 
    
 如果再加入风机、光伏、有载调压和电容器组，决策变量增加，目标函数变为各设备出力成本和损耗成本，我对此程序进行改动时总是无法正常运行，是不是对此程序的positon休整时，因为开关和各设备出力变量类型不相同导致的呢？，请问大致该如何进行修改程序？希望得到您的解答，麻烦了，谢谢您！ 
    
 这个没看到程序我也不太清楚问题出在哪，但是感觉加入决策变量不会不能正常运行，现在我程序中决策变量是每个Switch的状态，应该将其余决策变量加进去就行吧。 
  不过决策变量这么多的情况下，我个人感觉效果不会好，或者说这种比较简单的粒子群效果不会很好，我建议你可以将风机光伏之类的加入到优化程序中，让粒子群算法还是决策开关状态，然后拓扑定了后用二阶锥之类的优化算法算出各个设备出力，这样效果应该会比较好。

**Comment by guuififi** [comment]
嗯，我又检查了算法，改了一下网络参数就好了，麻烦您了，谢谢您的解答！

**Comment by ZoraTian** [comment]
不客气，以后有什么问题随时交流



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 14, 2023 20:47 PM
To: ***@***.***&gt;;
Cc: "Zora ***@***.******@***.***&gt;;
Subject: Re: [ZoraTian/ZoraTian-PSO_distribution_network_reconfiguration] Howto improve the code (Issue #1)




 
嗯，我又检查了算法，改了一下网络参数就好了，麻烦您了，谢谢您的解答！

**Comment by guuififi** [comment]
非常感谢师兄您的帮助！现在上hub得翻墙，回您比较慢，还望师兄海涵，哈哈哈...
